#!/bin/bash
rm archivo.sql
echo "use busqueda;" >> archivo.sql;
echo "delete from nutrigenomic;" >> archivo.sql
ls *.txt | while read fichero
do
cat "$fichero" | awk "BEGIN {FS=\"\t\";}{
if( NR > 1 && \$6 != \"\") {
print \"INSERT INTO nutrigenomic values (trim('\",\$1,\"'),\",\$2,\",\",\$3,\",\",\$5,\",\",\$6\",'$fichero');\";
}
}
"  >> archivo.sql
done
